namespace Altec.Api.Record.Printers;

public record PrinterInfo(
    int Dpi,
    string Model,
    string Serial,
    string Version,
    string PrintQuality,
    int Mileage,
    int LabelCounter,
    int Year,
    int Month,
    int Date,
    string MacAddressNet,
    string IpAddressNet,
    string NetworkName,
    string PrimaryDns,
    string MacAddressWlan,
    string IpAddressWlan,
    string SensorType,
    int Speed,
    int Density,
    int PaperWidth,
    int PaperHeight,
    int GapSize,
    int GapSizeOffset,
    int BlineSize,
    string Direction,
    string Ribbon,
    int PaperRollWidth,
    int Offset,
    int ShiftX,
    int ShiftY,
    string CountryCode,
    string CodePage,
    int GapOffset
);
